version: "3"
services:
  #PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: digitalocean.com/php
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "70:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network

  db:
    image: postgres
    restart: unless-stopped
    tty: true
    ports:
      - "5432:5432"
    environment:
<<<<<<< HEAD
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: postgres_user
      POSTGRES_DB: postgres_re_union
=======
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: union_export_import
>>>>>>> a332b07a3724244b2b20f6eb14a244775563df5f
    volumes:
      - database-data:/var/lib/postgresql/data/
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
#Volumes
volumes:
  database-data:
    driver: local